#define miINT8 1 // (null)
#define miUINT8 2 // (null)
#define miINT16 3 // (null)
#define miUINT16 4 // (null)
#define miINT32 5 // (null)
#define miUINT32 6 // (null)
#define miSINGLE 7 // (null)
#define miDOUBLE 9 // (null)
#define miINT64 12 // (null)
#define miUINT64 13 // (null)
#define miMATRIX 14 // (null)
#define miCOMPRESSED 15 // (null)
#define miUTF8 16 // (null)
#define miUTF16 17 // (null)
#define miUTF32 18 // (null)

